version: '2'
services:
    jhipstersamplemicroservicesapplication-app:
        image: jhipstersamplemicroservicesapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstersamplemicroservicesapplication-postgresql:5432/jhipsterSampleMicroServicesApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    jhipstersamplemicroservicesapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstersamplemicroservicesapplication-postgresql
