version: '2'
services:
    jhipstersamplemicroservicesapplication-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleMicroServicesApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleMicroServicesApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
